INSERT INTO Users (UserUsername, UserEmail, UserPassword) VALUES
('user1', 'user1@example.com', 'password1'),
('user2', 'user2@example.com', 'password2'),
('user3', 'user3@example.com', 'password3'),
('user4', 'user4@example.com', 'password4'),
('user5', 'user5@example.com', 'password5'),
('user6', 'user6@example.com', 'password6'),
('user7', 'user7@example.com', 'password7'),
('user8', 'user8@example.com', 'password8'),
('user9', 'user9@example.com', 'password9'),
('user10', 'user10@example.com', 'password10');


INSERT INTO Posts (PostTitle, PostBody, LikeCount, created_at, updated_at, Users_UserID) VALUES
('Post Title 1', 'This is the body of post 1.', 5, datetime('now'), datetime('now'), 1),
('Post Title 2', 'This is the body of post 2.', 3, datetime('now'), datetime('now'), 2),
('Post Title 3', 'This is the body of post 3.', 8, datetime('now'), datetime('now'), 3),
('Post Title 4', 'This is the body of post 4.', 2, datetime('now'), datetime('now'), 4),
('Post Title 5', 'This is the body of post 5.', 0, datetime('now'), datetime('now'), 5),
('Post Title 6', 'This is the body of post 6.', 4, datetime('now'), datetime('now'), 6),
('Post Title 7', 'This is the body of post 7.', 1, datetime('now'), datetime('now'), 7),
('Post Title 8', 'This is the body of post 8.', 7, datetime('now'), datetime('now'), 8),
('Post Title 9', 'This is the body of post 9.', 9, datetime('now'), datetime('now'), 9),
('Post Title 10', 'This is the body of post 10.', 6, datetime('now'), datetime('now'), 10);

INSERT INTO Comments (CommentBody, created_at, updated_at, Users_UserID, Posts_PostID) VALUES
('This is a comment on post 1 by user 2.', datetime('now'), datetime('now'), 2, 1),
('Interesting post 2! Here are my thoughts.', datetime('now'), datetime('now'), 3, 2),
('Loved this post, great job!', datetime('now'), datetime('now'), 4, 3),
('I have a different opinion on post 4.', datetime('now'), datetime('now'), 5, 4),
('Can you elaborate more on post 5?', datetime('now'), datetime('now'), 6, 5),
('Thanks for sharing post 6.', datetime('now'), datetime('now'), 7, 6),
('This was very informative for post 7.', datetime('now'), datetime('now'), 8, 7),
('I completely agree with post 8!', datetime('now'), datetime('now'), 9, 8),
('Not sure I understand post 9.', datetime('now'), datetime('now'), 10, 9),
('Post 10 made me think differently.', datetime('now'), datetime('now'), 1, 10),
('Another comment on post 1.', datetime('now'), datetime('now'), 3, 1),
('Yet another comment on post 2.', datetime('now'), datetime('now'), 4, 2),
('Amazing post 3! Keep it up.', datetime('now'), datetime('now'), 5, 3),
('Disagreeing respectfully on post 4.', datetime('now'), datetime('now'), 6, 4),
('What an insightful post 5.', datetime('now'), datetime('now'), 7, 5),
('Post 6 could use more data.', datetime('now'), datetime('now'), 8, 6),
('Thanks for clarifying in post 7.', datetime('now'), datetime('now'), 9, 7),
('Enjoyed reading post 8!', datetime('now'), datetime('now'), 10, 8),
('A great take in post 9.', datetime('now'), datetime('now'), 1, 9),
('So inspiring, loved post 10.', datetime('now'), datetime('now'), 2, 10);

INSERT INTO Comments (CommentBody, created_at, updated_at, Users_UserID, Posts_PostID) VALUES
('Post 1 is really insightful. Thanks for sharing!', datetime('now'), datetime('now'), 5, 1),
('I have a follow-up question about post 2.', datetime('now'), datetime('now'), 6, 2),
('Post 3 is spot on. Love the details.', datetime('now'), datetime('now'), 7, 3),
('Not sure if I fully agree with post 4.', datetime('now'), datetime('now'), 8, 4),
('Would you expand on the ideas in post 5?', datetime('now'), datetime('now'), 9, 5),
('Post 6 is a game changer. Kudos!', datetime('now'), datetime('now'), 10, 6),
('Reading post 7 made my day!', datetime('now'), datetime('now'), 1, 7),
('Post 8 has so much valuable information.', datetime('now'), datetime('now'), 2, 8),
('I found post 9 particularly enlightening.', datetime('now'), datetime('now'), 3, 9),
('Post 10 gave me a new perspective. Thank you.', datetime('now'), datetime('now'), 4, 10),
('Just dropping by to appreciate post 1 again.', datetime('now'), datetime('now'), 7, 1),
('Post 2 has inspired me to start my own project.', datetime('now'), datetime('now'), 8, 2),
('Commenting again on post 3. Truly wonderful.', datetime('now'), datetime('now'), 9, 3),
('Post 4 has some thought-provoking points.', datetime('now'), datetime('now'), 10, 4),
('I will share post 5 with my friends. Great job!', datetime('now'), datetime('now'), 1, 5),
('Post 6 raised an important question.', datetime('now'), datetime('now'), 2, 6),
('Couldn’t agree more with post 7. Perfect!', datetime('now'), datetime('now'), 3, 7),
('Post 8 is so well-written. Impressive!', datetime('now'), datetime('now'), 4, 8),
('Loved the examples in post 9.', datetime('now'), datetime('now'), 5, 9),
('Post 10 has great visuals to support its points.', datetime('now'), datetime('now'), 6, 10),
('This is my third comment on post 1. So good!', datetime('now'), datetime('now'), 9, 1),
('Post 2 deserves more likes!', datetime('now'), datetime('now'), 10, 2),
('I recommended post 3 to my colleagues.', datetime('now'), datetime('now'), 1, 3),
('Post 4 made me think differently about this topic.', datetime('now'), datetime('now'), 2, 4),
('Will there be a follow-up to post 5?', datetime('now'), datetime('now'), 3, 5),
('Post 6 could benefit from additional references.', datetime('now'), datetime('now'), 4, 6),
('Thank you for clarifying the concepts in post 7.', datetime('now'), datetime('now'), 5, 7),
('Post 8 is a treasure trove of knowledge.', datetime('now'), datetime('now'), 6, 8),
('Please write more posts like post 9!', datetime('now'), datetime('now'), 7, 9),
('Post 10 is an absolute masterpiece.', datetime('now'), datetime('now'), 8, 10);
