CREATE TABLE IF NOT EXISTS Users (
	UserID INTEGER PRIMARY KEY AUTOINCREMENT,
	UserUsername TEXT NOT NULL UNIQUE,
	UserEmail TEXT NOT NULL UNIQUE,
	UserPassword TEXT NOT NULL
);

    
CREATE TABLE IF NOT EXISTS Posts (
    PostID INTEGER PRIMARY KEY AUTOINCREMENT,
	PostTitle TEXT NOT NULL,
	PostBody TEXT NOT NULL,
	LikeCount INTEGER DEFAULT 0,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	Users_UserID INTEGER NOT NULL,
	FOREIGN KEY (Users_UserID) REFERENCES Users(UserID)
);

CREATE TABLE IF NOT EXISTS Comments (
    CommentID INTEGER PRIMARY KEY AUTOINCREMENT,
    CommentBody TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    Users_UserID INTEGER NOT NULL,
    Posts_PostID INTEGER NOT NULL,
    FOREIGN KEY (Users_UserID) REFERENCES Users(UserID),
    FOREIGN KEY (Posts_PostID) REFERENCES Posts(PostID)
);
